### ISSUE TITLE
Issue in 'Estimate MBES Coverage'; No depth values could be sampled

### ISSUE THREAD

**Issue by ArneL0001** [simondreutter/cruisetools#2]
Moin!

Thanks for the great tool set you've provided! Transitioning from Global Mapper to QGIS, these tools provide excellent capabilities. However, I'm struggling with the 'Estimate MBES Coverage' tool, which throws the following error:

.../python/plugins\cruisetools\planning\estimate_mbes_coverage.py", line 338, in processAlgorithm
raise Exception('No depth values could be sampled from the input raster!')
Exception: No depth values could be sampled from the input raster!

This is interesting as 'Load Bathymetry' and the other tools worked well and clearly show the bathymetry. This indicates to me that the depth values of my surfer grid were read. Exporting the grid via Cruise Tools and importing this file leads to the same failure of 'Estimate MBES Coverage'.

What am I doing wrong? Any idea what might be the cause?

Thank you & best regards
Arne

**Comment by simondreutter** [comment]
Hi Arne,

phew, good question. First of, when you export the grid with Cruise Tools via "Export Shaded Bathymetry", it will be an RGB raster without any depth values. But since you used "Load Bathymetry" successfully, I assume, the raster is a DEM raster supported by QGIS. To be honest, we almost exclusively work with GeoTIFFs and netCDF grids, and that's what we used to develop the module. Maybe if you use the native QGIS Export (right click in Layer Tree > Export) and export the (DEM!) raster as GeoTIFF or NC grid, that might do the trick?

Another thing would be, that your track geometry might not be 100% covered by the raster, which should lead to the same error. I personally usually use GEBCO, IBCSO or IBCAO for the "Estimate MBES Coverage" tool as its a consistent dataset (no NaN values) over a large area, and I never had any issues with it.

And the last idea, and I'm not sure whether we planned for this in the code or not, is that your projections don't fit or are not properly assigned in QGIS for the raster OR the vector. In this case the tool might try to sample at a wrong location, potentially outside of the raster area.

Let me know if you have success in this matter, otherwise I try to find time for some debugging, but time is short at the moment. :/

Cheers,
Simon

**Comment by ArneL0001** [comment]
Dear Simon,

thank you for the quick response! Exporting and importing as GeoTIFF has resolved the issue. Therefore, this was clearly a user error :-)

Thanks again for the cool tool!
Arne
